name: Nancy Rommelmann
favicon: null
layout_spectrum: 0.69855
typography_spectrum: 0.89251
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d1c18'
    - '#5b8b74'
    - '#333f31'
    - '#983a1a'
    - '#c88f44'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5212860847823322
purpose: []
