name: Nancy Rommelmann
favicon: null
layout_spectrum: 0.69855
typography_spectrum: 0.89251
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050309'
    - '#00eefb'
    - '#ffffff'
    - '#008f90'
    - '#ff2100'
  brandStrength: 0.9375
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5212860847823322
purpose: []
